In [1]:
import pandas as pd
import numpy as np

In [3]:
wiki_data_sets = [
    pd.read_pickle('Pick_wikidata_1_2500.pkl'),
    pd.read_pickle('Pick_wikidata_2500_5000.pkl'),
    pd.read_pickle('Pick_wikidata_5000_7500.pkl'),
    pd.read_pickle('Pick_wikidata_7500_10000.pkl'),
    pd.read_pickle('Pick_wikidata_10000_12658.pkl')
    ]

wikidata_dataset = pd.concat(wiki_data_sets,sort=False)
wikidata_dataset.shape

(12657, 2)

In [4]:
wikidata_dataset.head(5)

                  Name                            Wikidata_link
0       Abbott's Booby    https://www.wikidata.org/wiki/Q839854
0    Abbott's Starling  https://www.wikidata.org/wiki/Q27075615
0  Abd al Kuri Sparrow   https://www.wikidata.org/wiki/Q3056159
0        Abdim's Stork    https://www.wikidata.org/wiki/Q308199
0   Aberdare Cisticola   https://www.wikidata.org/wiki/Q1923584

In [6]:
birds = pd.read_pickle('..\..\data\Birds.pkl')

In [7]:
birds.head(5)

,Bird Original Name,Bird Original Name Telugu,Scientific Name,Scientific Name Telugu,Synonyms,Synonyms Telugu,Old latin name for bird,Old latin name for bird Telugu,Scientist,Scientist Telugu,...,Wiki_Description,Wiki_Description Telugu,Ebird_Link,Ebird_Description,Ebird_Description Telugu,Eol_Link,Eol_Description,Eol_Description Telugu,Dibird_Link,IUCN_link
0,Abbott's Babbler,అబోట్ యొక్క బాబ్లెర్,Malacocincla abbotti,మాలాకోసిన్లా అబ్బోటి,Abbott's Babbler,అబోట్ యొక్క బాబ్లెర్,NaN,NaN,Blyth,బ్లిత్,...,Abbott's babbler (Malacocincla abbotti) is a s...,అబోట్ యొక్క బాబ్లర్ (మలాకోసింక్లా అబోట్టి) అనే...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.iucnredlist.org/species/22715811/9...
1,Abbott's Booby,అబోట్ యొక్క బూబీ,Papasula abbotti,పాపసులా అబ్బోటి,Abbott's Booby,అబోట్ యొక్క బూబీ,Sula abbotti,సుల అబ్బోటి,Ridgway,రిడ్వే,...,Abbott's booby (Papasula abbotti) is an endang...,అబోట్ యొక్క బూబీ (పాపాసుల అబోట్టి) సులిడ్ కుటు...,https://ebird.org/species/abbboo2,"Gangly, stretched-out-looking black-and-white ...","గ్యాంగ్లీ, సాగదీసిన నలుపు-తెలుపు సముద్రపు పక్ష...",https://eol.org/pages/45513856,Papasula (Abbott's Booby) is a genus of birds ...,పాపసుల (అబాట్స్ బూబీ) అనేది సులిడే కుటుంబానికి...,https://dibird.com/species/abbotts-booby/,https://www.iucnredlist.org/species/22696649/1...
2,Abbott's Starling,అబోట్ యొక్క స్టార్లింగ్,Poeoptera femoralis,పూపెట్రా ఫెటోరిలిస్,Abbott's Starling,అబోట్ యొక్క స్టార్లింగ్,"Pholia femoralis, Pholidauges femoralis, Cinny...","ఫొలియా ఫెమోరిలిస్, ఫోలిడాగ్స్ ఫెటోరిలిస్, సినీ...",Richmond,రిచ్ మండ్,...,The Abbott's starling (Poeoptera femoralis) is...,అబోట్ యొక్క స్టార్లింగ్ (పోయోప్టెరా ఫెమోరాలిస్...,https://ebird.org/species/abbsta2,"A small, distinctive starling with a tiny rang...",కెన్యా మరియు టాంజానియాలో ఒక చిన్న శ్రేణితో ఒక ...,https://eol.org/pages/45515541,Poeoptera femoralis (Abbott's Starling) is a s...,పోయోప్టెరా ఫెమోరాలిస్ (అబాట్ యొక్క స్టార్లింగ్...,https://dibird.com/species/abbotts-starling/,https://www.iucnredlist.org/species/22710787/1...
3,Abd al Kuri Sparrow,అబ్ద్ అల్ కురి స్పారో,Passer hemileucus,పాసర్ హెమిలేయుస్,"Abd al Kuri Sparrow, Abd Al Kuri Sparrow","అబ్ద్ అల్ కురి స్పారో, అబ్ద్ అల్ కురి స్పారో",NaN,NaN,OgilvieGrant & Forbes,ఓగిల్వీగ్రాంట్ & ఫోర్బ్స్,...,Abd al Kuri (Arabic: عبد الكوري‎) is a rocky i...,అబ్ద్ అల్ కురి (అరబిక్: عبد الكوري) అనేది గార్...,NaN,NaN,NaN,NaN,NaN,NaN,https://dibird.com/species/abd-alkuri-sparrow/,https://www.iucnredlist.org/species/22735599/9...
4,Abdim's Stork,అబ్దిమ్ యొక్క స్టోర్క్,Ciconia abdimii,సికోనియా అబ్దిమిఐ,Abdim's Stork,అబ్దిమ్ యొక్క స్టోర్క్,"Sphenorrhynchus abdimii, Sphenorhynchus abdimii","స్ఫెనోరిన్చుస్ అబ్డిమి, స్ఫెన్నోరిచ్యున్చుస్ అ...",Lichtenstein,లిచ్టెన్ స్టెయిన్,...,"Abdim's stork (Ciconia abdimii), also known as...","అబ్దిమ్ కొంగ (సికోనియా అబ్దిమి), తెల్ల బొడ్డు ...",https://ebird.org/species/abdsto1,"A medium-sized, dark stork with a white belly....","తెల్లటి బొడ్డుతో మధ్యస్థ-పరిమాణ, ముదురు కొంగ. ...",https://eol.org/pages/45515774,Ciconia abdimii (Abdim's Stork) is a species o...,సికోనియా అబ్దిమి (అబ్డిమ్ కొంగ) అనేది సికోనిడే...,https://dibird.com/species/abdims-stork/,https://www.iucnredlist.org/species/22697673/9...

In [9]:
mask = wikidata_dataset['Wikidata_link'].isna()
sum(mask)

2460

In [10]:
wikidata_dataset.tail(3)

                     Name                            Wikidata_link
0          Zambian Barbet   https://www.wikidata.org/wiki/Q1261209
0  Zambian Yellow Warbler  https://www.wikidata.org/wiki/Q31874195
0         Zanzibar Boubou                                      NaN

In [11]:
birds.tail(3)

,Bird Original Name,Bird Original Name Telugu,Scientific Name,Scientific Name Telugu,Synonyms,Synonyms Telugu,Old latin name for bird,Old latin name for bird Telugu,Scientist,Scientist Telugu,...,Wiki_Description,Wiki_Description Telugu,Ebird_Link,Ebird_Description,Ebird_Description Telugu,Eol_Link,Eol_Description,Eol_Description Telugu,Dibird_Link,IUCN_link
12655,Zambian Barbet,జాంబియన్ బార్బెట్,Lybius chaplini,లిబియస్ చాప్లిని,"Zambian Barbet, Chaplin's Barbet","జాంబియన్ బార్బెట్, చాప్లిన్ యొక్క బార్బెట్",NaN,NaN,Clarke,క్లార్క్,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.iucnredlist.org/species/22681832/9...
12656,Zambian Yellow Warbler,జాంబియన్ ఎల్లో వార్బ్లెర్,Calamonastides bensoni,కాలోమోనాస్టిడ్స్ బెన్సోని,Zambian Yellow Warbler,జాంబియన్ ఎల్లో వార్బ్లెర్,NaN,NaN,Amadon,అమడన్,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.iucnredlist.org/species/103779336/...
12657,Zanzibar Boubou,జాంజిబార్ బౌబౌ,Laniarius sublacteus,లానియారియస్ సబ్లాక్టియస్,"Zanzibar Boubou, East Coast Boubou","జాంజిబార్ బౌబౌ, తూర్పు తీరం బౌబౌ",NaN,NaN,Cassin,కాసిన్,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.iucnredlist.org/species/22735541/1...

In [22]:
names_wiki = list(wikidata_dataset['Name'])
names_birds = list(birds['Bird Original Name'])
for i in names_wiki :
    if i not in names_birds:
        print(i)

In [23]:
birds.shape

(12658, 83)

In [24]:
wikidata_dataset.shape

(12657, 2)

In [26]:
q = []
for i in list(birds.columns):
    r = i.lower().split(' ')
    q.append('_'.join(r))
# k  = ''
# for w in q:
print(",".join(q))

bird_original_name,bird_original_name_telugu,scientific_name,scientific_name_telugu,synonyms,synonyms_telugu,old_latin_name_for_bird,old_latin_name_for_bird_telugu,scientist,scientist_telugu,founded,founded_telugu,kingdom,kingdom_telugu,subkingdom,subkingdom_telugu,infrakingdom,infrakingdom_telugu,phylum,phylum_telugu,subphylum,subphylum_telugu,infraphylum,infraphylum_telugu,superclass,superclass_telugu,class,class_telugu,order,order_telugu,family,family_telugu,genus,genus_telugu,species,species_telugu,conservation_status,conservation_status_telugu,habitat,habitat_telugu,country,country_telugu,geographic_distribution_includes,geographic_distribution_includes_telugu,biogeographic_realm,biogeographic_realm_telugu,population_growth,population_growth_telugu,breeding_region,breeding_region_telugu,breeding_subregion,breeding_subregion_telugu,life_span,life_span_telugu,altitude,altitude_telugu,visual_system,visual_system_telugu,auditory_system,auditory_system_telugu,hearing_range,hearing_range_telugu,hearing_threshold,hearing_threshold_telugu,locomotion,locomotion_telugu,mineralized_skeleton_contains,mineralized_skeleton_contains_telugu,body_mass,body_mass_telugu,wiki_link,image,references,wiki_description,wiki_description_telugu,ebird_link,ebird_description,ebird_description_telugu,eol_link,eol_description,eol_description_telugu,dibird_link,iucn_link

In [32]:
wikidata_dataset.set_index('Name')

                                                        Wikidata_link
Name
Abbott's Booby                  https://www.wikidata.org/wiki/Q839854
Abbott's Starling             https://www.wikidata.org/wiki/Q27075615
Abd al Kuri Sparrow            https://www.wikidata.org/wiki/Q3056159
Abdim's Stork                   https://www.wikidata.org/wiki/Q308199
Aberdare Cisticola             https://www.wikidata.org/wiki/Q1923584
...                                                               ...
Yucatan Rough-winged Swallow                                      NaN
Yunnan Parrotbill              https://www.wikidata.org/wiki/Q8061335
Zambian Barbet                 https://www.wikidata.org/wiki/Q1261209
Zambian Yellow Warbler        https://www.wikidata.org/wiki/Q31874195
Zanzibar Boubou                                                   NaN

[12657 rows x 1 columns]

In [41]:
wikidata_dataset.to_csv("links.csv")